name: Check sqlfluff

on:
  push:
    branches:
      - "feature/**"
      - main
    paths:
      - ".github/workflows/check_sqlfluff.yaml"
      - "**"

jobs:
  run-workflow:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run SQLFluff lint
        run: make run-sqlfluff-lint
